title: "ECE 312: Software Design and Implementation I"
description: "Course website for \"ECE 312: Software Design and Implementation I\" at UT Austin"
theme: just-the-docs

url: https://ece312-zhao.github.io

aux_links:
  Home: /
  Schedule: /schedule

# sass:
#   style: compressed

# include:
#   - assets/css
